In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn as sk

In [2]:
doctor = pd.read_excel("Final_Train_cleaned.xlsx")

In [3]:
doctor.columns

Index(['Unnamed: 0', 'Experience', 'Rating', 'Place', 'Profile',
       'Miscellaneous_Info', 'Fees', 'Qualification', 'Unnamed: 8',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [4]:
import pandas_profiling as pp

In [5]:
pp.ProfileReport(doctor)

In [6]:
doctor.isnull().sum()

Unnamed: 0            5961
Experience               0
Rating                3302
Place                   25
Profile                  0
Miscellaneous_Info    2620
Fees                     0
Qualification            0
Unnamed: 8            1962
Unnamed: 9            4590
Unnamed: 10           5585
Unnamed: 11           5842
Unnamed: 12           5926
Unnamed: 13           5949
Unnamed: 14           5955
Unnamed: 15           5957
Unnamed: 16           5960
dtype: int64

In [7]:
doctor.head(25)

,Unnamed: 0,Experience,Rating,Place,Profile,Miscellaneous_Info,Fees,Qualification,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,24 years experience,100%,"Kakkanad, Ernakulam",Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100,BHMS,MD - Homeopathy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,12 years experience,98%,"Whitefield, Bangalore",Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350,BAMS,MD - Ayurveda Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,9 years experience,NaN,"Mathikere - BEL, Bangalore",ENT Specialist,NaN,300,MBBS,MS - Otorhinolaryngology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,12 years experience,NaN,"Bannerghatta Road, Bangalore",Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250,BSc - Zoology,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,20 years experience,100%,"Keelkattalai, Chennai",Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,8 years experience,NaN,"Porur, Chennai",Ayurveda,NaN,100,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,42 years experience,NaN,"Karol Bagh, Delhi",Homeopath,NaN,200,BHMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,10 years experience,99%,"Arekere, Bangalore",Dentist,Dental Fillings Crowns and Bridges Fixing Impa...,200,BDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,14 years experience,NaN,"Old City, Hyderabad",General Medicine,NaN,100,MBBS,MD - General Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,23 years experience,NaN,"Athani, Ernakulam",Dentist,NaN,100,BSc,BDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,5 years experience,NaN,"Thousand Lights, Chennai",ENT Specialist,NaN,700,MBBS,MS,DNB - ENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,7 years experience,NaN,"Somajiguda, Hyderabad",Ayurveda,NaN,100,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,9 years experience,98%,"Coimbatore Racecourse, Coimbatore",Dentist,"98% 14 Feedback Coimbatore Racecourse, Coimbatore",200,BDS,MDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,21 years experience,NaN,"Jubilee Hills, Hyderabad",Dentist,Dental Crowns Facet Dental Dental prophylaxis,350,BDS,MDS - Oral & Maxillofacial Surgery,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,12 years experience,NaN,"Kondli, Delhi",ENT Specialist,NaN,500,MBBS,Diploma in Otorhinolaryngology (DLO),DNB - ENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,10 years experience,NaN,"Saroor Nagar, Hyderabad",General Medicine,NaN,200,MBBS,MD - General Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,24 years experience,NaN,"Tambaram West, Chennai",ENT Specialist,NaN,100,MBBS,Diploma in Otorhinolaryngology (DLO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,5 years experience,NaN,"Purasawakkam, Chennai",Homeopath,NaN,300,MBBS,MF- Homeopathy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,19 years experience,79%,"KPHB, Hyderabad",ENT Specialist,"79% 8 Feedback KPHB, Hyderabad",400,MBBS,MS - ENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,19 years experience,100%,"HSR Layout, Bangalore",General Medicine,"100% 4 Feedback HSR Layout, Bangalore",150,MBBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,21 years experience,100%,"Pollachi, Coimbatore",Dentist,"100% 7 Feedback Pollachi, Coimbatore",100,MDS,DNB,BDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,14 years experience,NaN,"Vasundhra Enclave, Delhi",ENT Specialist,Adenoid / Tonsil Surgery Rhinoplasty Laryngoscopy,500,MBBS,DNB - ENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,41 years experience,NaN,"Chembur, Mumbai",General Medicine,NaN,200,MBBS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,31 years experience,NaN,"Thammanam, Ernakulam",General Medicine,NaN,100,MBBS,Fellowship of College of General Practice (FCGP),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,23 years experience,NaN,"Andheri, Mumbai",Dermatologists,NaN,100,MBBS,DDVL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import re 
  
def extractMax(input):  
     numbers = re.findall('\d+',input)  
     numbers = map(int,numbers) 
     return int(max(numbers))

In [9]:
k=[]
for i in doctor['Experience']:
    k.append(extractMax(i))

In [10]:
doctor['Exp_years'] = k

In [11]:
doctor.dtypes

Unnamed: 0            float64
Experience             object
Rating                 object
Place                  object
Profile                object
Miscellaneous_Info     object
Fees                    int64
Qualification          object
Unnamed: 8             object
Unnamed: 9             object
Unnamed: 10            object
Unnamed: 11            object
Unnamed: 12            object
Unnamed: 13            object
Unnamed: 14            object
Unnamed: 15            object
Unnamed: 16            object
Exp_years               int64
dtype: object

In [12]:
doctor['Rating']=doctor['Rating'].fillna(0)

In [13]:
k=[]
c=0
for i in doctor['Rating']:
    k.append(extractMax(str(i)))
    if extractMax(str(i)) ==0:
        c=c+1
        
doctor['Rating'] = k

In [14]:
mean_value=sum(doctor['Rating'])/(len(k)-c)

In [15]:
doctor.head()

,Unnamed: 0,Experience,Rating,Place,Profile,Miscellaneous_Info,Fees,Qualification,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Exp_years
0,NaN,24 years experience,100,"Kakkanad, Ernakulam",Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100,BHMS,MD - Homeopathy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24
1,NaN,12 years experience,98,"Whitefield, Bangalore",Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350,BAMS,MD - Ayurveda Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
2,NaN,9 years experience,0,"Mathikere - BEL, Bangalore",ENT Specialist,NaN,300,MBBS,MS - Otorhinolaryngology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
3,NaN,12 years experience,0,"Bannerghatta Road, Bangalore",Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250,BSc - Zoology,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12
4,NaN,20 years experience,100,"Keelkattalai, Chennai",Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20

In [16]:
k=[]
c=0
for i in doctor['Rating']:
    if i == 0:
        k.append(mean_value)
    else:
        k.append(i)

In [17]:
doctor['Rating'] = k
doctor['Rating'] =round(doctor['Rating'])

In [18]:
doctor['Place'] = doctor['Place'].fillna('Whitefield, Bangalore')

In [19]:
doctor.isnull().sum()

Unnamed: 0            5961
Experience               0
Rating                   0
Place                    0
Profile                  0
Miscellaneous_Info    2620
Fees                     0
Qualification            0
Unnamed: 8            1962
Unnamed: 9            4590
Unnamed: 10           5585
Unnamed: 11           5842
Unnamed: 12           5926
Unnamed: 13           5949
Unnamed: 14           5955
Unnamed: 15           5957
Unnamed: 16           5960
Exp_years                0
dtype: int64

In [20]:
doctor['Miscellaneous_Info'] = doctor['Miscellaneous_Info'].fillna('Data Unknown')

In [21]:
city=[]
for i in doctor['Place']:
    if ',' in str(i):
        a,b =str(i).split(',',1)
        city.append(b)
    else:
        city.append(i)

In [22]:
len(city)

5961

In [23]:
doctor['city'] = city

In [24]:
doctor = doctor.drop(['Place'],axis=1)

In [25]:
doctor.head()

,Unnamed: 0,Experience,Rating,Profile,Miscellaneous_Info,Fees,Qualification,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Exp_years,city
0,NaN,24 years experience,100.0,Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100,BHMS,MD - Homeopathy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,Ernakulam
1,NaN,12 years experience,98.0,Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350,BAMS,MD - Ayurveda Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,Bangalore
2,NaN,9 years experience,95.0,ENT Specialist,Data Unknown,300,MBBS,MS - Otorhinolaryngology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,Bangalore
3,NaN,12 years experience,95.0,Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250,BSc - Zoology,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,Bangalore
4,NaN,20 years experience,100.0,Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,Chennai

In [26]:
doctor=doctor.drop(['Experience'],axis=1)

In [27]:
'''qualifications=[]
for i in doctor['Qualification']:
    b=[]
    if ',' in str(i):
        b =str(i).split(',')
        qualifications.append(b)
    else:
        b=str(i)
        qualifications.append(b)'''

"qualifications=[]\nfor i in doctor['Qualification']:\n    b=[]\n    if ',' in str(i):\n        b =str(i).split(',')\n        qualifications.append(b)\n    else:\n        b=str(i)\n        qualifications.append(b)"

In [28]:
'''len(qualifications)'''

'len(qualifications)'

In [29]:
'''doctor['Qualification']=qualifications'''

"doctor['Qualification']=qualifications"

In [30]:
from sklearn.linear_model import LinearRegression  
from sklearn.model_selection import train_test_split

In [31]:
'''max1=0
for i in doctor['Qualification']:
    if len(i) > max1:
        max1= len(i)
        index1=qualifications.index(i)
print(max1)
print(index1)'''

"max1=0\nfor i in doctor['Qualification']:\n    if len(i) > max1:\n        max1= len(i)\n        index1=qualifications.index(i)\nprint(max1)\nprint(index1)"

In [32]:
doctor.head()

,Unnamed: 0,Rating,Profile,Miscellaneous_Info,Fees,Qualification,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Exp_years,city
0,NaN,100.0,Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100,BHMS,MD - Homeopathy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,Ernakulam
1,NaN,98.0,Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350,BAMS,MD - Ayurveda Medicine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,Bangalore
2,NaN,95.0,ENT Specialist,Data Unknown,300,MBBS,MS - Otorhinolaryngology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,Bangalore
3,NaN,95.0,Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250,BSc - Zoology,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,Bangalore
4,NaN,100.0,Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250,BAMS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20,Chennai

In [33]:
doctor.columns

Index(['Unnamed: 0', 'Rating', 'Profile', 'Miscellaneous_Info', 'Fees',
       'Qualification', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Exp_years', 'city'],
      dtype='object')

In [34]:
'''doctor=doctor.drop(['Unnamed: 9', 'Unnamed: 10','Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16','Unnamed: 0'],axis=1)'''

In [35]:
 
    
'''doctor=doctor.drop(['Unnamed: 8'],axis=1)'''

In [36]:
doctor.head()

,Rating,Profile,Miscellaneous_Info,Fees,Qualification,Exp_years,city
0,100.0,Homeopath,"100% 16 Feedback Kakkanad, Ernakulam",100,BHMS,24,Ernakulam
1,98.0,Ayurveda,"98% 76 Feedback Whitefield, Bangalore",350,BAMS,12,Bangalore
2,95.0,ENT Specialist,Data Unknown,300,MBBS,9,Bangalore
3,95.0,Ayurveda,"Bannerghatta Road, Bangalore ₹250 Available on...",250,BSc - Zoology,12,Bangalore
4,100.0,Ayurveda,"100% 4 Feedback Keelkattalai, Chennai",250,BAMS,20,Chennai

In [37]:
out = doctor['Fees']
#,'Miscellaneous_Info'
x=doctor.drop(['Fees'],axis=1)
non_dummy_cols = ['rating','Exp_years'] 

dummy_cols = list(set(x.columns) - set(non_dummy_cols))
x = pd.get_dummies(x, columns=dummy_cols)

In [38]:
xtrain, xval, ytrain,yval=train_test_split(x, out, test_size=0.30, random_state=100)

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.ensemble import RandomForestRegressor

In [40]:
regressor = RandomForestRegressor()  
regressor.fit(xtrain, ytrain) 
validate = regressor.predict(xval)
validate

C:\Users\Aditya\Anaconda3\envs\tensor_flow\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([124.79004329, 158.16666667, 110.        , ..., 300.        ,
       309.08333333, 345.03333333])

In [41]:
print(yval)
print(validate)

1791    600
5616    100
200     250
4219    800
2558    400
3714    300
4318    500
1231    100
4531    300
2988    250
1268    300
3377    200
4458    200
5332    500
2252    900
1249    500
411     100
5819    100
966     300
2386    500
5913    700
1426    600
2287    300
2790    200
4326    250
3688    100
1514    700
2702    200
1321    700
1389    500
       ...
5927    400
2504    400
3838    100
5326    150
2717    500
4687    100
4883    700
2694    200
5723    100
2620    200
781     250
3932    100
2357    200
3800    300
5890    600
2175    300
4353    650
1464    100
4250    100
614      50
1522    300
1924    600
4480    800
2932    250
919     250
2061    250
1857    600
5163    100
3738    200
3794    200
Name: Fees, Length: 1789, dtype: int64
[124.79004329 158.16666667 110.         ... 300.         309.08333333
 345.03333333]